homeassistant:
  name: DWHome
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml

  whitelist_external_dirs:
    - /config

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

system_health:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

mobile_app:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform:  google_translate

r4s_kettler:
  device: 'hci1'
  mac: 'dc:bb:de:0c:3e:61'
  password: 'ab64e6f700f75c64'

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: 192.168.1.138
      mac: F0:B4:29:B3:F1:10
      key: !secret xiaomi_aqara_key

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.207
    name: roborock
    token: !secret vacuum_token

remote:
  - platform: xiaomi_miio
    host: 192.168.1.16
    name: irremote
    token: !secret remote_token

fan:
  - platform: xiaomi_miio
    host: 192.168.1.241
    token: !secret xiaomi_fan_token

yeelight:
  devices:
    192.168.1.140:
      name: hall_table_lamp

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 7

weather:
  - platform: openweathermap
    api_key: !secret weather_api_key

group: !include groups.yaml
script: !include_dir_merge_named includes/scripts
automation: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
light: !include includes/light.yaml
switch: !include includes/switch.yaml
binary_sensor: !include includes/binary_sensor.yaml
homekit: !include includes/HomeKit.yaml
recorder: !include includes/recorder.yaml
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml

